//TYPES PARA REGISTRO Y INICIO DE SECION
export const LISTADOREGISTRADOS = "LISTADOREGISTRADOS";
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const ERROR_API = "ERROR_API";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const CERRARSECION = "CERRARSECION";
///TYPES PARA EL BINGO
export const LISTADOBINGO = "LISTADOBINGO";
export const GUARDARLISTADOBINGO = "GUARDARLISTADOBINGO";
export const CREARTARJETABINGO = "CREARTARJETABINGO";
